title: <p align="center"> Ratnesh Zinzuwadia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ratneshzin/">LinkedIn</a> |
  <a href="https://github.com/ratneshflash">GitHub</a>
  
  <br>   
  I'm working on C++, Automotive Industry, Machine learning.
  Worked with Harman in C++, Linux, Integrity RTOS.
  Working in Mercedes Benz in Automotive domain since 2021.
  <br>
  </p>



theme: jekyll-theme-minimal